{
 "title": "Supervision Routeurs Cisco SNMP",
 "tags": [
  "snmp",
  "prometheus",
  "cisco",
  "supervision"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "router",
    "label": "Routeur",
    "query": {
     "query": "label_values(up{job=~\"snmp_interfaces|snmp_system\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Status VRRP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vrrpOperState{instance=\"$router\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime du routeur",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sysUpTime{job=\"snmp_system\", instance=\"$router\"} / 100"
    }
   ]
  },
  {
   "title": "Débit entrant total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ifHCInOctets{job=\"snmp_interfaces\", instance=\"$router\"}[1m]) * 8)"
    }
   ]
  },
  {
   "title": "Débit sortant total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ifHCOutOctets{job=\"snmp_interfaces\", instance=\"$router\"}[1m]) * 8)"
    }
   ]
  },
  {
   "title": "Disponibilité du routeur",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"snmp_system\", instance=\"$router\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Nombre d'interfaces opérationnelles",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ifOperStatus{instance=\"$router\", ifIndex=~\"1|2\"} == 1)"
    }
   ]
  },
  {
   "title": "État des interfaces",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "((ifOperStatus{instance=\"$router\", ifIndex=~\"1|2\"} == 1) * 1)\r\nOR\r\n((ifOperStatus{instance=\"$router\", ifIndex=~\"1|2\"} == 2) * 0)",
     "legendFormat": "Int{{ifIndex}}"
    }
   ]
  },
  {
   "title": "Débit sortant par interface",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(ifHCOutOctets{instance=\"$router\", ifIndex=~\"1|2\"}[1m]) * 8",
     "legendFormat": "Int{{ifIndex}}"
    }
   ]
  },
  {
   "title": "Utilisation int sur 1H",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(\r\n  5,\r\n  (\r\n    rate(ifHCInOctets{job=\"snmp_interfaces\",instance=~\"10.100.4.253|10.100.4.252\",ifIndex=~\"1|2\"}[1h]) +\r\n    rate(ifHCOutOctets{job=\"snmp_interfaces\",instance=~\"10.100.4.253|10.100.4.252\",ifIndex=~\"1|2\"}[1h])\r\n  ) * 8\r\n)",
     "legendFormat": "{{instance}} - Int{{ifIndex}}"
    }
   ]
  },
  {
   "title": "Débit entrant par interface",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(ifHCInOctets{instance=\"$router\", ifIndex=~\"1|2\"}[1m]) * 8",
     "legendFormat": "Int{{ifIndex}}"
    }
   ]
  }
 ]
}