{
 "title": "Supervision Web Blackbox",
 "tags": [
  "blackbox",
  "web"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Disponibilité des pages",
   "type": "stat",
   "gridPos": { "h": 14, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox_http\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Code HTTP",
   "type": "stat",
   "gridPos": { "h": 14, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_status_code{job=\"blackbox_http\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Activitée",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox_http\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Top pages lentes",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, probe_duration_seconds{job=\"blackbox_http\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Temps de réponse",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{job=\"blackbox_http\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}